"""init

Revision ID: b9e32a8bfe18
Revises: 
Create Date: 2025-10-29 18:22:09.984906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e32a8bfe18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('assignment_id', sa.String(length=128), nullable=True),
    sa.Column('hit_id', sa.String(length=128), nullable=True),
    sa.Column('completion_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_completion_code'), ['completion_code'], unique=False)

    op.create_table('trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('split', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_split'), ['split'], unique=False)

    op.create_table('ai_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_event_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_event_trial_id'), ['trial_id'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_trial_id'), ['trial_id'], unique=False)

    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('rt_ms', sa.Integer(), nullable=True),
    sa.Column('revealed_ai', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_trial_id'), ['trial_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_trial_id'))
        batch_op.drop_index(batch_op.f('ix_response_participant_id'))

    op.drop_table('response')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_trial_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_participant_id'))

    op.drop_table('assignment')
    with op.batch_alter_table('ai_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_event_trial_id'))
        batch_op.drop_index(batch_op.f('ix_ai_event_participant_id'))

    op.drop_table('ai_event')
    with op.batch_alter_table('trial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_split'))

    op.drop_table('trial')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_completion_code'))

    op.drop_table('participant')
    # ### end Alembic commands ###
